// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/orchestration.proto

package orchestration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNKNOWN       AgentStatus = 0
	AgentStatus_AGENT_STATUS_HEALTHY       AgentStatus = 1
	AgentStatus_AGENT_STATUS_BUSY          AgentStatus = 2
	AgentStatus_AGENT_STATUS_ERROR         AgentStatus = 3
	AgentStatus_AGENT_STATUS_SHUTTING_DOWN AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_HEALTHY",
		2: "AGENT_STATUS_BUSY",
		3: "AGENT_STATUS_ERROR",
		4: "AGENT_STATUS_SHUTTING_DOWN",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":       0,
		"AGENT_STATUS_HEALTHY":       1,
		"AGENT_STATUS_BUSY":          2,
		"AGENT_STATUS_ERROR":         3,
		"AGENT_STATUS_SHUTTING_DOWN": 4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestration_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_orchestration_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

type WorkItemStatus int32

const (
	WorkItemStatus_WORK_ITEM_STATUS_UNKNOWN   WorkItemStatus = 0
	WorkItemStatus_WORK_ITEM_STATUS_PENDING   WorkItemStatus = 1
	WorkItemStatus_WORK_ITEM_STATUS_ASSIGNED  WorkItemStatus = 2
	WorkItemStatus_WORK_ITEM_STATUS_RUNNING   WorkItemStatus = 3
	WorkItemStatus_WORK_ITEM_STATUS_COMPLETED WorkItemStatus = 4
	WorkItemStatus_WORK_ITEM_STATUS_FAILED    WorkItemStatus = 5
	WorkItemStatus_WORK_ITEM_STATUS_CANCELLED WorkItemStatus = 6
)

// Enum value maps for WorkItemStatus.
var (
	WorkItemStatus_name = map[int32]string{
		0: "WORK_ITEM_STATUS_UNKNOWN",
		1: "WORK_ITEM_STATUS_PENDING",
		2: "WORK_ITEM_STATUS_ASSIGNED",
		3: "WORK_ITEM_STATUS_RUNNING",
		4: "WORK_ITEM_STATUS_COMPLETED",
		5: "WORK_ITEM_STATUS_FAILED",
		6: "WORK_ITEM_STATUS_CANCELLED",
	}
	WorkItemStatus_value = map[string]int32{
		"WORK_ITEM_STATUS_UNKNOWN":   0,
		"WORK_ITEM_STATUS_PENDING":   1,
		"WORK_ITEM_STATUS_ASSIGNED":  2,
		"WORK_ITEM_STATUS_RUNNING":   3,
		"WORK_ITEM_STATUS_COMPLETED": 4,
		"WORK_ITEM_STATUS_FAILED":    5,
		"WORK_ITEM_STATUS_CANCELLED": 6,
	}
)

func (x WorkItemStatus) Enum() *WorkItemStatus {
	p := new(WorkItemStatus)
	*p = x
	return p
}

func (x WorkItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestration_proto_enumTypes[1].Descriptor()
}

func (WorkItemStatus) Type() protoreflect.EnumType {
	return &file_proto_orchestration_proto_enumTypes[1]
}

func (x WorkItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkItemStatus.Descriptor instead.
func (WorkItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN        MessageType = 0
	MessageType_MESSAGE_TYPE_CLARIFICATION  MessageType = 1
	MessageType_MESSAGE_TYPE_STATUS_UPDATE  MessageType = 2
	MessageType_MESSAGE_TYPE_AGENT_TO_AGENT MessageType = 3
	MessageType_MESSAGE_TYPE_AI_INSTRUCTION MessageType = 4
	MessageType_MESSAGE_TYPE_ERROR          MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_CLARIFICATION",
		2: "MESSAGE_TYPE_STATUS_UPDATE",
		3: "MESSAGE_TYPE_AGENT_TO_AGENT",
		4: "MESSAGE_TYPE_AI_INSTRUCTION",
		5: "MESSAGE_TYPE_ERROR",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN":        0,
		"MESSAGE_TYPE_CLARIFICATION":  1,
		"MESSAGE_TYPE_STATUS_UPDATE":  2,
		"MESSAGE_TYPE_AGENT_TO_AGENT": 3,
		"MESSAGE_TYPE_AI_INSTRUCTION": 4,
		"MESSAGE_TYPE_ERROR":          5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestration_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_orchestration_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{2}
}

// Agent registration
type RegisterAgentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Capabilities      []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata          *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MaxConcurrentWork int32                  `protobuf:"varint,7,opt,name=max_concurrent_work,json=maxConcurrentWork,proto3" json:"max_concurrent_work,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterAgentRequest) GetMaxConcurrentWork() int32 {
	if x != nil {
		return x.MaxConcurrentWork
	}
	return 0
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

// Work pulling (streaming)
type PullWorkRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AgentId               string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AvailableCapabilities []string               `protobuf:"bytes,2,rep,name=available_capabilities,json=availableCapabilities,proto3" json:"available_capabilities,omitempty"`
	MaxConcurrent         int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	LastHeartbeat         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PullWorkRequest) Reset() {
	*x = PullWorkRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullWorkRequest) ProtoMessage() {}

func (x *PullWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullWorkRequest.ProtoReflect.Descriptor instead.
func (*PullWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *PullWorkRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PullWorkRequest) GetAvailableCapabilities() []string {
	if x != nil {
		return x.AvailableCapabilities
	}
	return nil
}

func (x *PullWorkRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *PullWorkRequest) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type PullWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*PullWorkResponse_WorkItem
	//	*PullWorkResponse_KeepAlive
	//	*PullWorkResponse_NoWork
	Response      isPullWorkResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullWorkResponse) Reset() {
	*x = PullWorkResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullWorkResponse) ProtoMessage() {}

func (x *PullWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullWorkResponse.ProtoReflect.Descriptor instead.
func (*PullWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *PullWorkResponse) GetResponse() isPullWorkResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PullWorkResponse) GetWorkItem() *WorkItem {
	if x != nil {
		if x, ok := x.Response.(*PullWorkResponse_WorkItem); ok {
			return x.WorkItem
		}
	}
	return nil
}

func (x *PullWorkResponse) GetKeepAlive() *KeepAlive {
	if x != nil {
		if x, ok := x.Response.(*PullWorkResponse_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

func (x *PullWorkResponse) GetNoWork() *NoWorkAvailable {
	if x != nil {
		if x, ok := x.Response.(*PullWorkResponse_NoWork); ok {
			return x.NoWork
		}
	}
	return nil
}

type isPullWorkResponse_Response interface {
	isPullWorkResponse_Response()
}

type PullWorkResponse_WorkItem struct {
	WorkItem *WorkItem `protobuf:"bytes,1,opt,name=work_item,json=workItem,proto3,oneof"`
}

type PullWorkResponse_KeepAlive struct {
	KeepAlive *KeepAlive `protobuf:"bytes,2,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type PullWorkResponse_NoWork struct {
	NoWork *NoWorkAvailable `protobuf:"bytes,3,opt,name=no_work,json=noWork,proto3,oneof"`
}

func (*PullWorkResponse_WorkItem) isPullWorkResponse_Response() {}

func (*PullWorkResponse_KeepAlive) isPullWorkResponse_Response() {}

func (*PullWorkResponse_NoWork) isPullWorkResponse_Response() {}

type WorkItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkId               string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	WorkflowId           string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId               string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Action               string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	RequiredCapabilities []string               `protobuf:"bytes,5,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	Parameters           *structpb.Struct       `protobuf:"bytes,6,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Context              *structpb.Struct       `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	Timeout              *durationpb.Duration   `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RetryPolicy          *RetryPolicy           `protobuf:"bytes,9,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_proto_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *WorkItem) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *WorkItem) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkItem) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *WorkItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WorkItem) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *WorkItem) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *WorkItem) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkItem) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *WorkItem) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *WorkItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	mi := &file_proto_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *KeepAlive) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *KeepAlive) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoWorkAvailable struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RetryAfterSeconds int32                  `protobuf:"varint,2,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NoWorkAvailable) Reset() {
	*x = NoWorkAvailable{}
	mi := &file_proto_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoWorkAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoWorkAvailable) ProtoMessage() {}

func (x *NoWorkAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoWorkAvailable.ProtoReflect.Descriptor instead.
func (*NoWorkAvailable) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *NoWorkAvailable) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NoWorkAvailable) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// Result reporting
type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Result        *WorkResult            `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *ReportResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ReportResultRequest) GetResult() *WorkResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutionTime *durationpb.Duration   `protobuf:"bytes,4,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResult) Reset() {
	*x = WorkResult{}
	mi := &file_proto_orchestration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResult) ProtoMessage() {}

func (x *WorkResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResult.ProtoReflect.Descriptor instead.
func (*WorkResult) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{9}
}

func (x *WorkResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkResult) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *WorkResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkResult) GetExecutionTime() *durationpb.Duration {
	if x != nil {
		return x.ExecutionTime
	}
	return nil
}

func (x *WorkResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orchestration.AgentStatus" json:"status,omitempty"`
	HealthMetrics *structpb.Struct       `protobuf:"bytes,3,opt,name=health_metrics,json=healthMetrics,proto3" json:"health_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

func (x *HeartbeatRequest) GetHealthMetrics() *structpb.Struct {
	if x != nil {
		return x.HealthMetrics
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// Agent unregistration
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{12}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnregisterAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{13}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Common types
type RetryPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries      int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	BackoffDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=backoff_duration,json=backoffDuration,proto3" json:"backoff_duration,omitempty"`
	Timeout         *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_proto_orchestration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{14}
}

func (x *RetryPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryPolicy) GetBackoffDuration() *durationpb.Duration {
	if x != nil {
		return x.BackoffDuration
	}
	return nil
}

func (x *RetryPolicy) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// AI-native conversational messages
type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	FromAgentId   string                 `protobuf:"bytes,3,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	ToAgentId     string                 `protobuf:"bytes,4,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"` // empty for AI
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=orchestration.MessageType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_proto_orchestration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{15}
}

func (x *ConversationMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConversationMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ConversationMessage) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *ConversationMessage) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *ConversationMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConversationMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ClarificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Question      string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClarificationRequest) Reset() {
	*x = ClarificationRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClarificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarificationRequest) ProtoMessage() {}

func (x *ClarificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarificationRequest.ProtoReflect.Descriptor instead.
func (*ClarificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{16}
}

func (x *ClarificationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ClarificationRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ClarificationRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClarificationRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ClarificationRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ClarificationRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ClarificationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Response          string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AdditionalContext *structpb.Struct       `protobuf:"bytes,4,opt,name=additional_context,json=additionalContext,proto3" json:"additional_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClarificationResponse) Reset() {
	*x = ClarificationResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClarificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarificationResponse) ProtoMessage() {}

func (x *ClarificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarificationResponse.ProtoReflect.Descriptor instead.
func (*ClarificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{17}
}

func (x *ClarificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClarificationResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ClarificationResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClarificationResponse) GetAdditionalContext() *structpb.Struct {
	if x != nil {
		return x.AdditionalContext
	}
	return nil
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgentId   string                 `protobuf:"bytes,1,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	ToAgentId     string                 `protobuf:"bytes,2,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"` // empty for AI
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=orchestration.MessageType" json:"type,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_orchestration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{18}
}

func (x *AgentMessage) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *AgentMessage) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *AgentMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *AgentMessage) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_proto_orchestration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{19}
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_orchestration_proto protoreflect.FileDescriptor

const file_proto_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orchestration.proto\x12\rorchestration\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x01\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12.\n" +
	"\x13max_concurrent_work\x18\a \x01(\x05R\x11maxConcurrentWork\"\x8c\x01\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\rregistered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\xcd\x01\n" +
	"\x0fPullWorkRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\x16available_capabilities\x18\x02 \x03(\tR\x15availableCapabilities\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\xcc\x01\n" +
	"\x10PullWorkResponse\x126\n" +
	"\twork_item\x18\x01 \x01(\v2\x17.orchestration.WorkItemH\x00R\bworkItem\x129\n" +
	"\n" +
	"keep_alive\x18\x02 \x01(\v2\x18.orchestration.KeepAliveH\x00R\tkeepAlive\x129\n" +
	"\ano_work\x18\x03 \x01(\v2\x1e.orchestration.NoWorkAvailableH\x00R\x06noWorkB\n" +
	"\n" +
	"\bresponse\"\xc5\x03\n" +
	"\bWorkItem\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x123\n" +
	"\x15required_capabilities\x18\x05 \x03(\tR\x14requiredCapabilities\x127\n" +
	"\n" +
	"parameters\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x121\n" +
	"\acontext\x18\a \x01(\v2\x17.google.protobuf.StructR\acontext\x123\n" +
	"\atimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12=\n" +
	"\fretry_policy\x18\t \x01(\v2\x1a.orchestration.RetryPolicyR\vretryPolicy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"_\n" +
	"\tKeepAlive\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x0fNoWorkAvailable\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x13retry_after_seconds\x18\x02 \x01(\x05R\x11retryAfterSeconds\"|\n" +
	"\x13ReportResultRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x19.orchestration.WorkResultR\x06result\"J\n" +
	"\x14ReportResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb2\x02\n" +
	"\n" +
	"WorkResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06output\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06output\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12@\n" +
	"\x0eexecution_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rexecutionTime\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa1\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.orchestration.AgentStatusR\x06status\x12>\n" +
	"\x0ehealth_metrics\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rhealthMetrics\"j\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"K\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa9\x01\n" +
	"\vRetryPolicy\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12D\n" +
	"\x10backoff_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fbackoffDuration\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd6\x02\n" +
	"\x13ConversationMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\"\n" +
	"\rfrom_agent_id\x18\x03 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x04 \x01(\tR\ttoAgentId\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.orchestration.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x121\n" +
	"\acontext\x18\a \x01(\v2\x17.google.protobuf.StructR\acontext\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xfa\x01\n" +
	"\x14ClarificationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x121\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructR\acontext\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xbc\x01\n" +
	"\x15ClarificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12F\n" +
	"\x12additional_context\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x11additionalContext\"\xf6\x01\n" +
	"\fAgentMessage\x12\"\n" +
	"\rfrom_agent_id\x18\x01 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x02 \x01(\tR\ttoAgentId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.orchestration.MessageTypeR\x04type\x121\n" +
	"\acontext\x18\x06 \x01(\v2\x17.google.protobuf.StructR\acontext\"l\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId*\x90\x01\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14AGENT_STATUS_HEALTHY\x10\x01\x12\x15\n" +
	"\x11AGENT_STATUS_BUSY\x10\x02\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x03\x12\x1e\n" +
	"\x1aAGENT_STATUS_SHUTTING_DOWN\x10\x04*\xe6\x01\n" +
	"\x0eWorkItemStatus\x12\x1c\n" +
	"\x18WORK_ITEM_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18WORK_ITEM_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19WORK_ITEM_STATUS_ASSIGNED\x10\x02\x12\x1c\n" +
	"\x18WORK_ITEM_STATUS_RUNNING\x10\x03\x12\x1e\n" +
	"\x1aWORK_ITEM_STATUS_COMPLETED\x10\x04\x12\x1b\n" +
	"\x17WORK_ITEM_STATUS_FAILED\x10\x05\x12\x1e\n" +
	"\x1aWORK_ITEM_STATUS_CANCELLED\x10\x06*\xc1\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_CLARIFICATION\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_STATUS_UPDATE\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_AGENT_TO_AGENT\x10\x03\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_AI_INSTRUCTION\x10\x04\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x052\xdd\x05\n" +
	"\x14OrchestrationService\x12Z\n" +
	"\rRegisterAgent\x12#.orchestration.RegisterAgentRequest\x1a$.orchestration.RegisterAgentResponse\x12O\n" +
	"\bPullWork\x12\x1e.orchestration.PullWorkRequest\x1a\x1f.orchestration.PullWorkResponse(\x010\x01\x12W\n" +
	"\fReportResult\x12\".orchestration.ReportResultRequest\x1a#.orchestration.ReportResultResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.orchestration.HeartbeatRequest\x1a .orchestration.HeartbeatResponse\x12`\n" +
	"\x0fUnregisterAgent\x12%.orchestration.UnregisterAgentRequest\x1a&.orchestration.UnregisterAgentResponse\x12^\n" +
	"\x10OpenConversation\x12\".orchestration.ConversationMessage\x1a\".orchestration.ConversationMessage(\x010\x01\x12a\n" +
	"\x14RequestClarification\x12#.orchestration.ClarificationRequest\x1a$.orchestration.ClarificationResponse\x12J\n" +
	"\vSendMessage\x12\x1b.orchestration.AgentMessage\x1a\x1e.orchestration.MessageResponseB2Z0github.com/ztdp/orchestrator/proto/orchestrationb\x06proto3"

var (
	file_proto_orchestration_proto_rawDescOnce sync.Once
	file_proto_orchestration_proto_rawDescData []byte
)

func file_proto_orchestration_proto_rawDescGZIP() []byte {
	file_proto_orchestration_proto_rawDescOnce.Do(func() {
		file_proto_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)))
	})
	return file_proto_orchestration_proto_rawDescData
}

var file_proto_orchestration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_orchestration_proto_goTypes = []any{
	(AgentStatus)(0),                // 0: orchestration.AgentStatus
	(WorkItemStatus)(0),             // 1: orchestration.WorkItemStatus
	(MessageType)(0),                // 2: orchestration.MessageType
	(*RegisterAgentRequest)(nil),    // 3: orchestration.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 4: orchestration.RegisterAgentResponse
	(*PullWorkRequest)(nil),         // 5: orchestration.PullWorkRequest
	(*PullWorkResponse)(nil),        // 6: orchestration.PullWorkResponse
	(*WorkItem)(nil),                // 7: orchestration.WorkItem
	(*KeepAlive)(nil),               // 8: orchestration.KeepAlive
	(*NoWorkAvailable)(nil),         // 9: orchestration.NoWorkAvailable
	(*ReportResultRequest)(nil),     // 10: orchestration.ReportResultRequest
	(*ReportResultResponse)(nil),    // 11: orchestration.ReportResultResponse
	(*WorkResult)(nil),              // 12: orchestration.WorkResult
	(*HeartbeatRequest)(nil),        // 13: orchestration.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 14: orchestration.HeartbeatResponse
	(*UnregisterAgentRequest)(nil),  // 15: orchestration.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 16: orchestration.UnregisterAgentResponse
	(*RetryPolicy)(nil),             // 17: orchestration.RetryPolicy
	(*ConversationMessage)(nil),     // 18: orchestration.ConversationMessage
	(*ClarificationRequest)(nil),    // 19: orchestration.ClarificationRequest
	(*ClarificationResponse)(nil),   // 20: orchestration.ClarificationResponse
	(*AgentMessage)(nil),            // 21: orchestration.AgentMessage
	(*MessageResponse)(nil),         // 22: orchestration.MessageResponse
	(*structpb.Struct)(nil),         // 23: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 25: google.protobuf.Duration
}
var file_proto_orchestration_proto_depIdxs = []int32{
	23, // 0: orchestration.RegisterAgentRequest.metadata:type_name -> google.protobuf.Struct
	24, // 1: orchestration.RegisterAgentResponse.registered_at:type_name -> google.protobuf.Timestamp
	24, // 2: orchestration.PullWorkRequest.last_heartbeat:type_name -> google.protobuf.Timestamp
	7,  // 3: orchestration.PullWorkResponse.work_item:type_name -> orchestration.WorkItem
	8,  // 4: orchestration.PullWorkResponse.keep_alive:type_name -> orchestration.KeepAlive
	9,  // 5: orchestration.PullWorkResponse.no_work:type_name -> orchestration.NoWorkAvailable
	23, // 6: orchestration.WorkItem.parameters:type_name -> google.protobuf.Struct
	23, // 7: orchestration.WorkItem.context:type_name -> google.protobuf.Struct
	25, // 8: orchestration.WorkItem.timeout:type_name -> google.protobuf.Duration
	17, // 9: orchestration.WorkItem.retry_policy:type_name -> orchestration.RetryPolicy
	24, // 10: orchestration.WorkItem.created_at:type_name -> google.protobuf.Timestamp
	24, // 11: orchestration.KeepAlive.timestamp:type_name -> google.protobuf.Timestamp
	24, // 12: orchestration.NoWorkAvailable.timestamp:type_name -> google.protobuf.Timestamp
	12, // 13: orchestration.ReportResultRequest.result:type_name -> orchestration.WorkResult
	23, // 14: orchestration.WorkResult.output:type_name -> google.protobuf.Struct
	25, // 15: orchestration.WorkResult.execution_time:type_name -> google.protobuf.Duration
	23, // 16: orchestration.WorkResult.metadata:type_name -> google.protobuf.Struct
	24, // 17: orchestration.WorkResult.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 18: orchestration.HeartbeatRequest.status:type_name -> orchestration.AgentStatus
	23, // 19: orchestration.HeartbeatRequest.health_metrics:type_name -> google.protobuf.Struct
	24, // 20: orchestration.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	25, // 21: orchestration.RetryPolicy.backoff_duration:type_name -> google.protobuf.Duration
	25, // 22: orchestration.RetryPolicy.timeout:type_name -> google.protobuf.Duration
	2,  // 23: orchestration.ConversationMessage.type:type_name -> orchestration.MessageType
	23, // 24: orchestration.ConversationMessage.context:type_name -> google.protobuf.Struct
	24, // 25: orchestration.ConversationMessage.timestamp:type_name -> google.protobuf.Timestamp
	23, // 26: orchestration.ClarificationRequest.context:type_name -> google.protobuf.Struct
	24, // 27: orchestration.ClarificationRequest.timestamp:type_name -> google.protobuf.Timestamp
	23, // 28: orchestration.ClarificationResponse.additional_context:type_name -> google.protobuf.Struct
	2,  // 29: orchestration.AgentMessage.type:type_name -> orchestration.MessageType
	23, // 30: orchestration.AgentMessage.context:type_name -> google.protobuf.Struct
	3,  // 31: orchestration.OrchestrationService.RegisterAgent:input_type -> orchestration.RegisterAgentRequest
	5,  // 32: orchestration.OrchestrationService.PullWork:input_type -> orchestration.PullWorkRequest
	10, // 33: orchestration.OrchestrationService.ReportResult:input_type -> orchestration.ReportResultRequest
	13, // 34: orchestration.OrchestrationService.Heartbeat:input_type -> orchestration.HeartbeatRequest
	15, // 35: orchestration.OrchestrationService.UnregisterAgent:input_type -> orchestration.UnregisterAgentRequest
	18, // 36: orchestration.OrchestrationService.OpenConversation:input_type -> orchestration.ConversationMessage
	19, // 37: orchestration.OrchestrationService.RequestClarification:input_type -> orchestration.ClarificationRequest
	21, // 38: orchestration.OrchestrationService.SendMessage:input_type -> orchestration.AgentMessage
	4,  // 39: orchestration.OrchestrationService.RegisterAgent:output_type -> orchestration.RegisterAgentResponse
	6,  // 40: orchestration.OrchestrationService.PullWork:output_type -> orchestration.PullWorkResponse
	11, // 41: orchestration.OrchestrationService.ReportResult:output_type -> orchestration.ReportResultResponse
	14, // 42: orchestration.OrchestrationService.Heartbeat:output_type -> orchestration.HeartbeatResponse
	16, // 43: orchestration.OrchestrationService.UnregisterAgent:output_type -> orchestration.UnregisterAgentResponse
	18, // 44: orchestration.OrchestrationService.OpenConversation:output_type -> orchestration.ConversationMessage
	20, // 45: orchestration.OrchestrationService.RequestClarification:output_type -> orchestration.ClarificationResponse
	22, // 46: orchestration.OrchestrationService.SendMessage:output_type -> orchestration.MessageResponse
	39, // [39:47] is the sub-list for method output_type
	31, // [31:39] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_orchestration_proto_init() }
func file_proto_orchestration_proto_init() {
	if File_proto_orchestration_proto != nil {
		return
	}
	file_proto_orchestration_proto_msgTypes[3].OneofWrappers = []any{
		(*PullWorkResponse_WorkItem)(nil),
		(*PullWorkResponse_KeepAlive)(nil),
		(*PullWorkResponse_NoWork)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestration_proto_goTypes,
		DependencyIndexes: file_proto_orchestration_proto_depIdxs,
		EnumInfos:         file_proto_orchestration_proto_enumTypes,
		MessageInfos:      file_proto_orchestration_proto_msgTypes,
	}.Build()
	File_proto_orchestration_proto = out.File
	file_proto_orchestration_proto_goTypes = nil
	file_proto_orchestration_proto_depIdxs = nil
}
